import type { Store } from "../types";

export const DEMO_CREATOR_ID = "c2";

export const DEMO_STORES: Store[] = [
  {
    id: "store-local-1",
    // Single demo-owned shop (matches online beta Canopy ownership).
    ownerUserId: DEMO_CREATOR_ID,
    name: "Canopy Canvas",
    handle: "canopycanvas",
    storeType: "both",
    description: "Local needlepoint shop with painted canvases, threads, and finishing.",
    avatar: "/assets/needlepoint-hero.png",
    coverImage: "/assets/persimmon-garden-pillow.jpg",
    websiteUrl: "https://example.com/canopy",
    location: "Portland, OR",
    city: "Portland",
    region: "OR",
    country: "US",
    shipsNationwide: true,
    specialties: ["painted canvases", "finishing", "threads"],
    products: [
      {
        id: "sp1",
        storeId: "store-local-1",
        name: "Persimmon Garden pillow canvas",
        description: "18 mesh painted canvas for a lush fruit pillow.",
        image: "/assets/persimmon-garden-pillow.jpg",
        priceLabel: "from $86",
        externalUrl: "https://example.com/canopy/persimmon",
        category: "canvas",
      },
      {
        id: "sp2",
        storeId: "store-local-1",
        name: "Bookshop Door printed canvas",
        description: "18 mesh storefront scene for framed pieces.",
        image: "/assets/bookshop-door-canvas.jpg",
        priceLabel: "from $74",
        externalUrl: "https://example.com/canopy/bookshop-door",
        category: "canvas",
      },
      {
        id: "sp3",
        storeId: "store-local-1",
        name: "Blue Hydrangea belt canvas",
        description: "Narrow belt canvas with botanical repeat.",
        image: "/assets/blue-hydrangea-belt.jpg",
        priceLabel: "from $48",
        externalUrl: "https://example.com/canopy/hydrangea-belt",
        category: "canvas",
      },
    ],
    projectCount: 3,
    followerCount: 12,
    latitude: 45.5202471,
    longitude: -122.674194,
    postalCode: "97205",
  },
  {
    id: "store-online-1",
    ownerUserId: null,
    name: "Thread & Tonic",
    handle: "threadandtonic",
    storeType: "online",
    description: "Online specialty threads and silk blends for advanced stitchers.",
    avatar: "/assets/needlepoint-hero.png",
    coverImage: "/assets/blue-hydrangea-belt.jpg",
    websiteUrl: "https://example.com/threadtonic",
    location: "Ships nationwide",
    city: "",
    region: "",
    country: "US",
    postalCode: "",
    shipsNationwide: true,
    specialties: ["silk", "metallic", "kits"],
    products: [
      {
        id: "sp4",
        storeId: "store-online-1",
        name: "Silk blend starter pack",
        description: "Assorted silk blends for advanced stitchers.",
        image: "/assets/blue-hydrangea-belt.jpg",
        priceLabel: "$42",
        externalUrl: "https://example.com/threadtonic/silk-pack",
        category: "thread",
      },
      {
        id: "sp5",
        storeId: "store-online-1",
        name: "Metallic accent kit",
        description: "Kreinik-style accents for roofs and trims.",
        image: "/assets/tiny-ski-lodge-ornament.jpg",
        priceLabel: "$28",
        externalUrl: "https://example.com/threadtonic/metallic",
        category: "thread",
      },
      {
        id: "sp6",
        storeId: "store-online-1",
        name: "Holiday ornament finishing pack",
        description: "Cording and felt backs for small gifts.",
        image: "/assets/tiny-ski-lodge-ornament.jpg",
        priceLabel: "$19",
        externalUrl: "https://example.com/threadtonic/finishing",
        category: "finishing",
      },
    ],
    projectCount: 3,
    followerCount: 28,
    latitude: null,
    longitude: null,
  },
  {
    id: "store-local-2",
    ownerUserId: null,
    name: "Bookshop Windows LNS",
    handle: "bookshopwindows",
    storeType: "local",
    description: "Neighborhood LNS hosting stitch-alongs and custom finishing.",
    avatar: "/assets/needlepoint-hero.png",
    coverImage: "/assets/bookshop-door-canvas.jpg",
    websiteUrl: "https://example.com/bookshop",
    location: "Austin, TX",
    city: "Austin",
    region: "TX",
    country: "US",
    shipsNationwide: false,
    specialties: ["local pickup", "classes", "finishing"],
    products: [
      {
        id: "sp7",
        storeId: "store-local-2",
        name: "Custom finishing — small pillow",
        description: 'Local finishing for pillows under 16".',
        image: "/assets/persimmon-garden-pillow.jpg",
        priceLabel: "from $65",
        externalUrl: "https://example.com/bookshop/finishing",
        category: "finishing",
      },
      {
        id: "sp8",
        storeId: "store-local-2",
        name: "July stitch-along kit add-on",
        description: "Threads pulled for bookshop-themed SAL.",
        image: "/assets/bookshop-door-canvas.jpg",
        priceLabel: "$36",
        externalUrl: "https://example.com/bookshop/sal-kit",
        category: "kit",
      },
      {
        id: "sp9",
        storeId: "store-local-2",
        name: "Neighborhood class voucher",
        description: "In-store beginner basketweave session.",
        image: "/assets/needlepoint-hero.png",
        priceLabel: "$45",
        externalUrl: "https://example.com/bookshop/class",
        category: "class",
      },
    ],
    projectCount: 1,
    followerCount: 6,
    latitude: 30.2711286,
    longitude: -97.7436995,
    postalCode: "78701",
  },
];

export const STORAGE_KEYS = {
  projects: "needle-point-project:projects",
  collections: "needle-point-project:collections",
  follows: "needle-point-project:follows",
  storeFollows: "needle-point-project:storeFollows",
  stitchAlong: "needle-point-project:stitchAlong",
  stitchAlongs: "needle-point-project:stitchAlongs",
  dismissDiscover: "needle-point-project:dismissDiscover",
  dismissStudio: "needle-point-project:dismissStudio",
  interests: "needle-point-project:interests",
  skill: "needle-point-project:skill",
};
