import type { Collection, Creator, Project, StitchAlong } from "./types";

const img = (id: string, crop = "entropy") =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=82&crop=${crop}`;

const asset = (name: string) => `/assets/${name}`;

export const creators: Creator[] = [
  {
    id: "c1",
    name: "Mara Chen",
    handle: "mara_stitches",
    avatar: img("photo-1494790108377-be9c29b29330"),
    bio: "Modern florals, painted canvases, and calm Sunday stitching notes from a Brooklyn apartment.",
    skillLevel: "advanced stitcher",
    isCreator: true,
    location: "Brooklyn, NY",
    followers: 12840,
    links: [
      { label: "Pattern shop", url: "https://example.com/mara-patterns" },
      { label: "Classes", url: "https://example.com/mara-classes" },
      { label: "Instagram", url: "https://instagram.com/example" },
    ],
    specialties: ["florals", "silk threads", "painted canvas"],
  },
  {
    id: "c2",
    name: "June Mercer",
    handle: "threadandtonic",
    avatar: img("photo-1517841905240-472988babdf9"),
    bio: "Beginner-friendly ornaments, finishing ideas, and honest notes about thread substitutions.",
    skillLevel: "confident beginner",
    isCreator: false,
    location: "Austin, TX",
    followers: 934,
    links: [{ label: "Project notebook", url: "https://example.com/june-notebook" }],
    specialties: ["ornaments", "holiday", "wool"],
  },
  {
    id: "c3",
    name: "Canopy Canvas Co.",
    handle: "canopycanvas",
    avatar: img("photo-1527980965255-d3b416303d12"),
    bio: "Small-batch canvases inspired by gardens, bookshops, heirloom linens, and weekend markets.",
    skillLevel: "creator shop",
    isCreator: true,
    location: "Charleston, SC",
    followers: 22100,
    links: [
      { label: "Shop canvases", url: "https://example.com/canopy" },
      { label: "Newsletter", url: "https://example.com/canopy-news" },
    ],
    specialties: ["canvases", "kits", "botanical"],
  },
];

export const initialProjects: Project[] = [
  {
    id: "p1",
    title: "Persimmon Garden Pillow",
    creatorId: "c1",
    image: asset("persimmon-garden-pillow.jpg"),
    status: "in progress",
    difficulty: "advanced",
    category: "pillow",
    canvasType: "18 mesh painted canvas",
    stitchTypes: ["basketweave", "french knots", "leaf stitch"],
    materials: ["Planet Earth silk", "DMC pearl cotton", "Kreinik braid"],
    colors: ["persimmon", "olive", "cream"],
    patternSource: "Canopy Canvas Co.",
    patternUrl: "https://example.com/persimmon-garden",
    notes: "Testing raised stitches for the fruit and keeping the background matte so the silk can shine.",
    likes: 184,
    isLiked: false,
    isSaved: true,
    visibility: "public",
    progress: 62,
    updates: [
      {
        id: "u1",
        date: "Jul 1",
        milestone: "Border mapped",
        note: "Swapped the border to a cashmere stitch so the corners feel softer.",
        image: asset("persimmon-garden-pillow.jpg"),
        likes: 43,
        comments: [{ id: "cm1", author: "June", body: "That border choice is perfect." }],
      },
      {
        id: "u2",
        date: "Jun 24",
        milestone: "Fruit texture",
        note: "French knots in two oranges gave the persimmons a little dimension.",
        image: asset("persimmon-garden-pillow.jpg"),
        likes: 61,
        comments: [],
      },
    ],
  },
  {
    id: "p2",
    title: "Tiny Ski Lodge Ornament",
    creatorId: "c2",
    image: asset("tiny-ski-lodge-ornament.jpg"),
    status: "finished",
    difficulty: "beginner",
    category: "ornament",
    canvasType: "13 mesh canvas",
    stitchTypes: ["continental", "scotch stitch"],
    materials: ["DMC wool", "silk lame braid"],
    colors: ["evergreen", "cranberry", "snow"],
    patternSource: "Vintage chart adaptation",
    patternUrl: "https://example.com/ski-lodge",
    notes: "A quick gift stitch with a metallic roof and simple finishing plan.",
    likes: 96,
    isLiked: true,
    isSaved: false,
    visibility: "public",
    progress: 100,
    updates: [
      {
        id: "u3",
        date: "Jun 28",
        milestone: "Finished",
        note: "Blocked and ready for cording. The roof sparkle was worth the extra thread management.",
        image: asset("tiny-ski-lodge-ornament.jpg"),
        likes: 28,
        comments: [{ id: "cm2", author: "Mara", body: "Saving this for my winter queue." }],
      },
    ],
  },
  {
    id: "p3",
    title: "Bookshop Door Canvas",
    creatorId: "c3",
    image: asset("bookshop-door-canvas.jpg"),
    status: "planned",
    difficulty: "intermediate",
    category: "framed piece",
    canvasType: "18 mesh printed canvas",
    stitchTypes: ["tent stitch", "brick stitch", "satin stitch"],
    materials: ["Vineyard silk", "DMC floss", "Rainbow Gallery velvet"],
    colors: ["teal", "brass", "rose"],
    patternSource: "Canopy Canvas Co.",
    patternUrl: "https://example.com/bookshop-door",
    notes: "Queued for the July stitch-along with velvet for the awning.",
    likes: 211,
    isLiked: false,
    isSaved: true,
    visibility: "public",
    progress: 8,
    updates: [
      {
        id: "u4",
        date: "Jul 2",
        milestone: "Kitted",
        note: "Pulled thread options and chose a warmer brass for the doorknob.",
        image: asset("bookshop-door-canvas.jpg"),
        likes: 55,
        comments: [],
      },
    ],
  },
  {
    id: "p4",
    title: "Blue Hydrangea Belt",
    creatorId: "c1",
    image: asset("blue-hydrangea-belt.jpg"),
    status: "paused",
    difficulty: "intermediate",
    category: "accessory",
    canvasType: "18 mesh belt canvas",
    stitchTypes: ["basketweave", "mosaic stitch"],
    materials: ["Anchor floss", "Pepper Pot silk"],
    colors: ["cornflower", "navy", "leaf"],
    patternSource: "Self-drafted from garden photos",
    patternUrl: "https://example.com/hydrangea-belt-notes",
    notes: "Paused until the background blue arrives. Testing whether mosaic reads too busy at belt scale.",
    likes: 73,
    isLiked: false,
    isSaved: false,
    visibility: "public",
    progress: 34,
    updates: [
      {
        id: "u5",
        date: "Jun 12",
        milestone: "Color test",
        note: "The middle value needs to be cooler before I commit to the full repeat.",
        image: asset("blue-hydrangea-belt.jpg"),
        likes: 19,
        comments: [],
      },
    ],
  },
];

export const initialCollections: Collection[] = [
  {
    id: "col1",
    name: "Next on the stretcher bars",
    description: "Saved projects with stitch ideas for the next month.",
    projectIds: ["p1", "p3"],
  },
  {
    id: "col2",
    name: "Holiday finishing ideas",
    description: "Ornaments, metallic thread notes, and quick gifts.",
    projectIds: ["p2"],
  },
];

export const stitchAlong: StitchAlong = {
  id: "sa1",
  title: "July Bookshop Windows Stitch-Along",
  hostId: "c3",
  dates: "Jul 6 - Aug 17, 2026",
  theme: "Doors, windows, shelves, and tiny storefront details.",
  description:
    "A six-week stitch-along for bookish canvases. Join with a new canvas or submit progress on an existing storefront, library, or shelf project.",
  rules: [
    "Submit one public project with a bookshop, library, door, or shelf theme.",
    "Add at least one progress update during the stitch-along window.",
    "Share thread substitutions so other stitchers can learn from your choices.",
  ],
  participantProjectIds: ["p3", "p1"],
  joined: false,
};
